# Generated by Django 5.1.1 on 2024-10-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(related_name='label', to='labels.label'),
        ),
    ]
