# Generated by Django 5.1 on 2024-09-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='customer',
            new_name='executor',
        ),
    ]
