# Generated by Django 5.1 on 2024-09-25 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='label', to='labels.label'
            ),
            preserve_default=False,
        ),
    ]
