# Generated by Django 5.1.1 on 2024-10-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_labels_task_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
