# Generated by Django 5.1 on 2024-09-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_status_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='title',
        ),
    ]
