# Generated by Django 5.1.1 on 2024-10-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_rename_name_status_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='name',
        ),
    ]
